# This workflow exclusively and specifically only checks the
# kumascript test suite.
# But if a package gets upgraded (e.g. Dependabot making a PR)
# that should test the kumascript suite too because the packages
# might have (and we've seen it happen!) an impact on the suite.

# Note that lint checking and stuff for files with `kumascript/**`
# is done with the general testing workflow.

name: Kumascript unit testing

on:
  pull_request:
    paths:
      - kumascript/**
      - .github/workflows/pr-kumascript.yml
      - package-lock.json

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install all npm packages
        run: npm ci

      - name: Unit testing kumascript
        env:
          CONTENT_ROOT: testing/content/files
        run: npm run test:kumascript
