# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing Yari

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install all npm packages
        run: npm ci

      - name: Lint prettier
        run: npm run prettier-check

      - name: Lint ESLint
        run: npm run eslint

      - name: Lint stylelint
        run: npm run stylelint

      - name: Check TypeScript
        run: npm run check:tsc

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install all npm packages
        run: npm ci

      - name: Unit testing client
        run: npm run test:client

      - name: Build and start server
        id: server
        env:
          ENV_FILE: .env.testing
        run: |
          npm run build:prepare
          npm run build

          npm run start:static-server > /tmp/stdout.log 2> /tmp/stderr.log &
          sleep 1
          curl --fail --retry-connrefused --retry 5 http://localhost:5042 > /dev/null

      - name: Functional testing
        run: |
          npm run test:testing
          npm run test:headless

      - name: Basic m2h tool testing
        env:
          ENV_FILE: .env.testing
        run: |
          npm run m2h -- markdown/tool/m2h --locale en-US
          diff -s testing/content/files/en-us/markdown/tool/m2h/index.html testing/content/files/en-us/markdown/tool/m2h/expected.html

      - name: Debug server's stdout and stderr if tests failed
        if: failure() && steps.server.outcome != 'skipped'
        run: |
          echo "STDOUT..................................................."
          cat /tmp/stdout.log
          echo ""
          echo "STDERR..................................................."
          cat /tmp/stderr.log
